CREATE TABLE app.users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

	name VARCHAR(150) NOT NULL,
	email VARCHAR(255),

	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
	
);
